//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by MapEditor.rc
//
#define IDS_DIB_TOO_BIG                 4
#define IDS_CANNOT_LOAD_DIB             5
#define IDS_CANNOT_SAVE_DIB             6
#define IDS_CANT_CREATE_TILESET         7
#define IDS_BAD_DIB_DIMENSIONS          8
#define IDS_DIB_TOO_SMALL               9
#define IDS_CANNOT_COPY_DIB             10
#define IDS_NOT_8BIT_TILESET            11
#define IDS_NO_DUPLICATES               12
#define IDS_INCOMPATIBLE_TILESET        13
#define IDS_ASK_COPY_PALETTE            14
#define IDS_CANT_COMPACT_TILESET        15
#define IDS_CANT_COMPACT_ON_SAVE        16
#define IDS_TILESET_EXPORT_FILTER       17
#define IDS_RESIZE_MAY_LOSE_DATA        18
#define IDS_ASK_CROP                    19
#define IDS_ASK_OVERWRITE_GROUP         20
#define IDS_CATEGORY_FORMAT             21
#define IDS_GROUP_FORMAT                22
#define IDS_ANIM                        23
#define IDS_FIND_STATUS_FORMAT          24
#define IDS_REVERT_MAY_LOSE_DATA        25
#define IDS_BASE_LAYER                  26
#define IDS_OVERLAY_LAYER               27
#define IDS_ATTRIBUTE_LAYER             28
#define IDS_MAP_EXPORT_FILTER           29
#define IDS_BITMAP_PROPERTIES           30
#define IDS_ASK_DELETE_CATEGORY         31
#define IDS_TILECATEGORIES              32
#define IDS_LAYERBARNAME                33
#define IDS_ADDING_PLAYER               34
#define IDS_NOTHING_TO_EXPORT           35
#define IDS_TILE                        36
#define IDS_GROUP                       37
#define IDS_OBJECT                      38
#define IDS_CATEGORY                    39
#define IDS_ROW_COLUMN_FORMAT           40
#define IDS_POINT_FORMAT                41
#define IDS_ITEMS_FOUND_FORMAT          42
#define IDS_AMV_MAPSIZE                 43
#define IDS_AMV_TILESIZE                44
#define IDS_AMV_TILEDEPTH               45
#define IDS_AMV_BASELAYER               46
#define IDS_AMV_OBJECTLAYER             47
#define IDS_AMV_TILE                    48
#define IDS_AMV_TILESET                 49
#define IDS_GROUPCATEGORIES             50
#define IDS_GROUPS                      51
#define IDS_TILES                       52
#define IDS_BAD_OBJECT_NAME             53
#define IDS_OBJECT_LAYER                54
#define IDS_SELECT_OBJECTSET            55
#define IDS_SELECT_TILESET              56
#define IDS_ADDING_CATEGORY             57
#define IDS_LOADING_FILE                58
#define IDS_OBJECTS                     59
#define IDS_AMV_BADOBJECT               60
#define IDS_AMV_TILESETBM               61
#define IDS_NO_PALETTE                  62
#define IDS_WARN_PALETTE_CHANGE         63
#define IDS_ATTRIBUTE                   64
#define IDS_VALUE                       65
#define IDS_ADJUST_ATTRIBUTE            66
#define IDS_DELETE_TILEATTRIBUTE        67
#define IDS_ASK_NEWATTRIBUTELAYER       68
#define IDS_CANT_UNDO_REPLACE           69
#define IDS_ITEMS_SELECTED_FORMAT       70
#define IDS_AMV_SCENARIONAME            71
#define IDS_SELECT_SCENARIOSET          72
#define IDS_SCENARIO                    73
#define IDS_DEPLOYMENT_ERROR            74
#define IDS_SCENARIO_DEPLOYED           75
#define IDS_RESOURCE_DEPLOYMENT_ERROR   76
#define IDS_AMV_BADUNITTOTAL            77
#define IDS_DOORWAY                     78
#define IDS_GETINCREMENT                79
#define IDS_GETDECREMENT                80
#define IDS_ATTRIBUTES                  81
#define IDS_SEQUENCE                    82
#define IDS_TILESET_ATTRIBUTES          83
#define IDS_COPY_TILEDATA               84
#define IDS_BITMAP_TOO_SMALL            85
#define IDS_NOT_8BIT_BITMAP             86
#define IDS_REMOVING_TILE               87
#define IDS_REMAPPING_OBJECT            88
#define IDS_TYPE                        89
#define IDS_LAYER                       90
#define IDS_DUPLICATE_LAYER             91
#define IDS_ATTRIBUTE_INFO              92
#define IDS_ASK_DELETE_LAYER            93
#define IDS_AMV_MAPDESC                 94
#define IDS_FRAMES                      95
#define IDS_UNTITLED                    96
#define IDS_AMV_OBJOFFMAP               96
#define IDD_ABOUTBOX                    100
#define CG_IDS_CANNOT_OPEN_CLIPBOARD    102
#define CG_IDS_CANNOT_GET_CLIPBOARD_DATA 103
#define IDS_CANT_RESIZE_MAP             104
#define IDS_CANT_ADD_TILE               105
#define IDS_PROPSHT_CAPTION             106
#define IDS_DUPLICATE_OBJECT_NAME       107
#define IDS_DUPLICATE_OBJECT_NUMBER     108
#define CG_IDD_PROGRESS                 109
#define CG_IDS_PROGRESS_CAPTION         110
#define CG_IDD_LAYERBAR                 118
#define ID_INDICATOR_ITEMTYPE           120
#define ID_INDICATOR_ITEMID             121
#define ID_INDICATOR_ITEMPOS            122
#define ID_INDICATOR_ITEMINFO           123
#define IDB_SPLASH                      124
#define IDD_PROP_ANIM                   126
#define IDR_MAINFRAME                   128
#define IDR_MAPTYPE                     129
#define IDD_TILESET                     130
#define IDR_OBJECTSET                   130
#define IDR_SCENARIOSET                 131
#define IDR_TILESETTYPE                 153
#define IDS_CME                         155
#define IDD_NEWMAP                      156
#define IDD_NEWCATERGORY                159
#define IDD_NEWGROUP                    161
#define IDR_TILESET                     162
#define IDD_NEWTILESET                  167
#define IDD_FINDDUPLICATES              178
#define IDD_REMOVEDUPLICATES            179
#define IDB_CHECK                       187
#define IDB_CROSS                       191
#define IDD_PROP_GENERAL                216
#define IDD_LAYERS                      217
#define IDD_EXPORT_MAPBMP               222
#define IDB_DELETE                      230
#define IDB_DOWN                        231
#define IDB_NEW                         232
#define IDB_UP                          233
#define IDD_NEWLAYER                    234
#define IDD_SHOWUSAGE                   235
#define IDD_CATEGORIES                  237
#define IDD_OBJECTSET                   238
#define IDD_EMPTYVIEW                   239
#define IDR_ARMYMAP                     240
#define IDR_ARMYTILESET                 241
#define IDD_ATTRIBUTEVIEW               244
#define IDD_SCENARIO                    245
#define IDD_NEWATTRIBUTE                247
#define IDD_ATTRIBUTES                  248
#define IDR_TILESETPOPUP                249
#define IDD_PROP_SCENARIO               251
#define IDD_DOORWAYS                    260
#define IDD_GETNUMBER                   262
#define IDB_STATE                       264
#define IDB_DOORWAY                     265
#define IDB_ROUTE                       266
#define IDB_START                       267
#define IDB_END                         268
#define IDD_PROP_AMEN                   273
#define IDC_HAND_CURSOR                 275
#define IDB_CYCLEF                      276
#define IDB_CYCLEB                      277
#define IDB_CYCLEN                      278
#define IDD_COMPUTE_LAYER               279
#define IDD_XRing                       283
#define IDD_ORing                       284
#define IDD_RINGVIEW                    285
#define IDD_OBJTEXT                     286
#define IDD_SCRIPTS                     289
#define IDD_NEWMOG                      291
#define IDD_SELECT                      292
#define IDD_EXPAND                      293
#define IDD_ROTATE                      294
#define IDC_TILESET_TAB                 1000
#define CG_IDC_PROGDLG_PROGRESS         1003
#define CG_IDC_PROGDLG_PERCENT          1004
#define IDC_TILESET_LIST                1018
#define IDC_MAP_BROWSE                  1028
#define IDC_MAP_OBSBROWSE               1029
#define IDC_MAP_SCENBROWSE              1030
#define IDC_MAP_TILESET                 1036
#define IDC_GROUP_NAME                  1037
#define IDC_MAP_OBJECTSET               1038
#define IDC_MAP_SCENARIOSET             1039
#define IDC_TILESET_BROWSE              1054
#define IDC_TILESET_DATA                1055
#define IDC_TILESET_ITEM                1060
#define IDC_TILESET_TOLERANCE           1078
#define IDC_TILESET_MAXTOL              1080
#define IDC_REMDUP_LIST                 1081
#define IDC_REMDUP_FOUND                1087
#define IDC_REMDUP_REMOVE               1088
#define IDC_CATEGORY_TITLE              1093
#define IDC_COMPACT_ON_SAVE             1098
#define IDC_USE_BITMAP_WIDTH            1099
#define IDC_BITMAP_WIDTH                1100
#define IDC_TILE_HEIGHT                 1105
#define IDC_TILE_WIDTH                  1106
#define IDC_MAP_HEIGHT                  1107
#define IDC_MAP_WIDTH                   1108
#define IDC_PROGRESS_STATUS             1114
#define IDC_NEWMAP_REPEAT               1116
#define IDC_OUTLINE_PREVIEW             1117
#define IDC_TRANSPARENT_COLOR           1134
#define IDC_EXPORT_ALL                  1137
#define IDC_EXPORT_VISIBLE_LAYERS       1138
#define IDC_EXPORT_ACTIVE_LAYERS        1139
#define IDC_EXPORT_STANDARD             1140
#define IDC_EXPORT_CUSTOM               1141
#define IDC_BITMAP_PERCENTAGE           1143
#define IDC_BITMAP_HEIGHT               1146
#define IDC_BITMAP_DEPTH                1151
#define IDC_BITMAP_PROPERTIES           1152
#define IDC_TILESET_VIEW                1157
#define IDC_ACTIVATE_LAYER              1159
#define IDC_LAYER_TYPE                  1160
#define IDC_PREVIEW_ACTIVE              1161
#define IDC_USAGE_THRESHOLD             1162
#define IDC_CATEGORY_LIST               1163
#define IDC_OBJECTSET_TAB               1167
#define IDC_OBJECTSET_ITEM              1168
#define IDC_OBJECTSET_LIST              1169
#define IDC_DATA_CTRL                   1171
#define IDC_ATTRIBUTE_DEFAULT           1176
#define IDC_ATTRIBUTE_VALUE_UPDOWN      1177
#define IDC_SHOW_FULL_OBJECTNAME        1185
#define IDC_DRAW_OFFSCREEN              1186
#define IDC_SCENARIO_TOTAL              1190
#define IDC_SCENARIO_ITEMID             1191
#define IDC_SCENARIO_RESOURCES          1194
#define IDC_SCENARIO_DEPLOYED           1195
#define IDC_ATTRIBUTE_COLOR             1204
#define IDC_ATTRIBUTE_DSTRING           1207
#define IDC_ATTRIBUTE_VALUE             1208
#define IDC_ATTRIBUTE_BITCOUNT          1210
#define IDC_ATTRIBUTE_BITS              1211
#define IDC_ATTRIBUTE_MAX               1212
#define IDC_ATTRIBUTE_NAME              1213
#define IDC_VERSION                     1214
#define IDC_ATTRIBUTE_DEFAULT_UPDOWN    1224
#define IDC_ATTRIBUTE_LIST              1225
#define IDC_ATTRIBUTE_LABEL             1227
#define IDC_ATTRIBUTE_SOLID             1230
#define IDC_ATTRIBUTE_GREYSCALE         1231
#define IDC_SCENARIO_UNITNAME           1232
#define IDC_ATTRIBUTE_INVERTEDGREY      1232
#define IDC_SCENARIO_RSRCNAME           1233
#define IDC_ATTRIBUTE_TILELAYER         1234
#define IDC_ATTRIBUTE_UPDATE_DEFAULT    1235
#define IDC_ATTRIBUTE_UPDATE_TILES      1236
#define IDC_DOORWAY_COMPUTE             1244
#define IDC_DOORWAY_LINE_COLOR          1246
#define IDC_DOORWAY_POINT_COLOR         1247
#define IDC_DOORWAY_ROUTE_COLOR         1248
#define IDC_DOORWAY_LIST                1249
#define IDC_GET_NUMBER                  1250
#define IDC_GET_NUMBER_CAPTION          1251
#define IDC_ATTRIBUTE_SHOW_OBJECTS      1254
#define IDC_DOORWAY_ROUTE               1255
#define IDC_DOORWAY_START               1256
#define IDC_DOORWAY_END                 1257
#define IDC_DOORWAY_CLEAR               1258
#define IDC_NEW_ITEM                    1259
#define IDC_DELETE_ITEM                 1260
#define IDC_DOORWAY_START_TEXT          1260
#define IDC_UP_ITEM                     1261
#define IDC_DOORWAY_END_TEXT            1261
#define IDC_DOWN_ITEM                   1262
#define IDS_DOORWAY_START_TEXT          1263
#define IDC_EDIT1                       1263
#define IDS_DOORWAY_END_TEXT            1264
#define IDC_EDIT2                       1264
#define IDC_LAYER_LIST                  1264
#define IDC_EDIT3                       1265
#define IDC_MAP_COLOR                   1265
#define IDS_RANDALL                     1265
#define IDC_EDIT4                       1266
#define IDC_MAP_DESC                    1266
#define IDS_RANDSEL                     1266
#define IDC_EDIT5                       1267
#define IDS_MOG                         1267
#define IDC_EDIT6                       1268
#define IDC_OBJECTSET_CYLCE             1268
#define IDS_MOGEXT                      1268
#define IDC_EDIT7                       1269
#define IDC_SEQUENCE_LIST               1269
#define IDS_EXTMOG                      1269
#define IDC_EDIT8                       1270
#define IDS_VIEWAREA                    1270
#define IDC_SOURCE_LAYER                1271
#define IDS_TILESADDED                  1271
#define IDC_INPUT_VALUE                 1272
#define IDS_TILESREM                    1272
#define IDC_LEFT                        1273
#define IDC_UPLIN                       1274
#define IDC_UPDL                        1274
#define IDC_UPL                         1275
#define IDC_PAGES                       1275
#define IDC_UPM                         1276
#define IDC_UPR                         1277
#define IDC_TEXT                        1277
#define IDC_UPDR                        1278
#define IDC_RIGHT                       1279
#define IDC_SLIST                       1279
#define IDC_LWDR                        1280
#define IDC_FILE                        1280
#define IDC_LWR                         1281
#define IDC_NAME                        1281
#define IDC_LWM                         1282
#define IDC_BX                          1282
#define IDC_LWL                         1283
#define IDC_BY                          1283
#define IDC_LWDL                        1284
#define IDC_EX                          1284
#define IDC_EY                          1285
#define IDC_UPRIN                       1286
#define IDC_RESET                       1286
#define IDC_UPLOUT                      1287
#define IDC_TOP                         1287
#define IDC_UPMOUT                      1288
#define IDC_BOTTOM                      1288
#define IDC_UPROUT                      1289
#define IDC_WIDTH                       1289
#define IDC_MDLOUT                      1290
#define IDC_HEIGHT                      1290
#define IDC_MD                          1291
#define IDC_TILESTAT                    1291
#define IDC_MDROUT                      1292
#define IDC_TILES                       1292
#define IDC_LWLOUT                      1293
#define IDC_ROTATE                      1293
#define IDC_LWDOUT                      1294
#define IDC_RT_CW                       1294
#define IDC_LWROUT                      1295
#define IDC_RT_CCW                      1295
#define IDC_LWLIN                       1296
#define IDC_FLIP                        1296
#define IDC_LWRIN                       1297
#define IDC_FL_H                        1297
#define IDC_FL_V                        1298
#define IDC_RT_FULLCW                   1299
#define ID_INSERT_NEWGROUP              32880
#define ID_INSERT_NEWCATEGORY           32881
#define ID_VIEW_OVERVIEW                32891
#define ID_WINDOW_CLOSEALL              32893
#define ID_TILESET_ADDGROUP             32895
#define ID_TILESET_READONLY             32897
#define ID_EDIT_PROPERTIES              32899
#define ID_TILESET_FINDDUP              32901
#define ID_TILESET_COMPACT              32902
#define ID_FILE_EXPORT                  32903
#define ID_EDIT_SELECT                  32904
#define ID_EDIT_CROP                    32908
#define ID_EDIT_SELECT_NONE             32910
#define ID_FILE_IMPORT                  32911
#define ID_EDIT_OPTIONS                 32912
#define ID_VIEW_OPTIONS                 32913
#define ID_CANCEL_OP                    32922
#define ID_SELECT_ADD                   32923
#define ID_FILE_REVERT                  32924
#define ID_VIEW_LAYERS                  32929
#define ID_FILE_OPENOLD                 32930
#define ID_VIEW_LAYERBAR                32932
#define ID_OBJECT_BOTTOM                32937
#define ID_OBJECT_TOP                   32938
#define ID_EDIT_CLONE                   32939
#define ID_TILESET_FINDUNUSED           32943
#define ID_TILESET_SHOWUSAGE            32944
#define ID_TILESET_TILECATEGORIES       32947
#define ID_TILESET_GROUPCATEGORIES      32948
#define ID_OBJECT_FORWARD               32949
#define ID_OBJECT_BACK                  32950
#define ID_LEFT                         32952
#define ID_RIGHT                        32953
#define ID_UP                           32954
#define ID_DOWN                         32955
#define ID_TILESET_USEPALETTE           32956
#define ID_TILESET_REMAPTOPALETTE       32957
#define ID_ATTRIBUTE_DECIMAL            32958
#define IDC_ATTRIBUTES                  32960
#define ID_EDIT_WITHATTRIBUTES          32965
#define ID_OBJECT_RENAME                32966
#define ID_EDIT_UPDATEATTRIBUTES        32968
#define ID_VIEW_GRID                    32970
#define ID_SELECT_TOP                   32972
#define ID_LAYERS_ACTIVATETOP           32985
#define ID_LAYERS_ACTIVATEBOTTOM        32986
#define ID_LAYERS_ACTIVATENEXT          32992
#define ID_LAYERS_ACTIVATEPREVIOUS      32993
#define ID_LAYERS_ARRANGE               32994
#define ID_EDIT_RANDOMIZE               32996
#define ID_TILESET_TILEATTRIBUTES       33005
#define ID_EDIT_ATTRIBUTES              33006
#define ID_OBJECT_SORT                  33007
#define ID_OBJECT_REMAP                 33008
#define ID_VIEW_REPOSITION              33013
#define ID_OBJECT_FLIPHORIZONTAL        33014
#define ID_OBJECT_ANIMATE               33015
#define ID_LAYERS_COMPUTE               33016
#define ID_TILESET_CMECATEGORIES        33032
#define ID_EDIT_SCRIPTS                 33033
#define ID_OBJECT_CREATEMOG             33034
#define ID_EDIT_SELECTDLG               33035
#define ID_EDIT_VIEWABLE                33036
#define ID_EDIT_EXPAND                  33037
#define ID_ROTATE                       33038
#define ID_EDIT_ROTATE                  33039
#define ID_VIEW_TOGGLERULER             33040

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        296
#define _APS_NEXT_COMMAND_VALUE         33041
#define _APS_NEXT_CONTROL_VALUE         1300
#define _APS_NEXT_SYMED_VALUE           127
#endif
#endif
