//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by ArmyMen.rc
//
#define IDS_DDRAW_ERROR_DDC             1
#define IDS_DDRAW_ERROR_SCL             2
#define IDC_TEAM_BUTTON                 2
#define IDS_DDRAW_ERROR_SDM             3
#define IDS_DDRAW_ERROR_CSFB            4
#define IDS_DDRAW_ERROR_GAS             5
#define IDS_DDRAW_ERROR_CC              6
#define IDS_DDRAW_ERROR_SH              7
#define IDS_DDRAW_ERROR_SC              8
#define IDS_DDRAW_ERROR_CSS0            9
#define IDS_DDRAW_ERROR_CSS1            10
#define IDS_DDRAW_ERROR_CSS2            11
#define IDS_DDRAW_ERROR_CSS3            12
#define IDS_DDRAW_ERROR_CSN             13
#define IDS_DDRAW_ERROR_RS              14
#define IDS_DINPUT_ERROR_DIC            15
#define IDS_DINPUT_ERROR_ED             16
#define IDS_DINPUT_ERROR_CD             17
#define IDS_DINPUT_ERROR_SP             18
#define IDS_DINPUT_ERROR_A              19
#define IDS_DPLAY_ERROR_CP              20
#define IDS_DPLAY_ERROR_IDC             21
#define IDS_DPLAY_ERROR_CP2             22
#define IDS_DPLAY_ERROR_JS              23
#define IDS_DPLAY_ERROR_CS              24
#define IDS_DDRAW_ERROR_CSBB            25
#define IDS_DUEL_CLASSNAME              26
#define IDS_DUEL_MSG_UNKNOWN            27
#define IDS_DUEL_ERROR_TITLE            28
#define IDS_DUEL_TITLE                  29
#define IDS_STRING2                     30
#define IDS_DDUTIL_ERROR_LI             38
#define IDS_DDUTIL_ERROR_DDCB           39
#define IDS_DDUTIL_ERROR_CCDC           40
#define IDS_WIZARD_ERROR_GSG            41
#define IDS_DINPUT_ERROR_DF             42
#define IDS_DPLAY_ERROR_IDC2            43
#define IDS_DSOUND_LOADWAVES            44
#define IDS_DSOUND_DUPBUF               45
#define IDS_DPLAY_ERROR_SL              46
#define IDS_DPLAY_ERROR_GPLD            47
#define IDS_DPLAY_ERROR_SPLD            48
#define IDS_DPLAY_ERROR_GPRD            49
#define IDS_DPLAY_ERROR_SPRD            50
#define IDS_DPLAY_ERROR_GSD             51
#define IDS_DPLAY_ERROR_EP              52
#define IDS_DPLAY_ERROR_ES              53
#define IDS_DPLAY_ERROR_C               54
#define IDS_DPLAY_ERROR_R               55
#define IDS_DPLAY_ERROR_DP              56
#define IDS_DPLOBBY_ERROR_R             57
#define IDS_DPLOBBY_ERROR_GCS           58
#define IDS_DPLOBBY_ERROR_SCS           59
#define IDS_DPLOBBY_ERROR_C             60
#define IDS_DPLOBBY_ERROR_CONNECT       61
#define IDS_DUEL_HOST_TITLE             62
#define IDS_DUEL_HOST_RELIABLE_TITLE    63
#define IDS_DUEL_RELIABLE_TITLE         64
#define IDS_DPERR_BUSY                  65
#define IDS_DPERR_INVALIDOBJECT         66
#define IDS_DPERR_INVALIDPARAMS         67
#define IDS_DPERR_INVALIDPLAYER         68
#define IDS_DPERR_SENDTOOBIG            69
#define IDS_DPERR_NOBUFFERS             70
#define IDS_DPERR_BUFFERTOOSMALL        71
#define IDD_ABOUTBOX                    100
#define IDB_OPEN_SESSION                101
#define IDB_CLOSED_SESSION              102
#define IDB_PLAYER                      103
#define IDD_GAMESETUP                   108
#define IDD_CONNECT_STATUS              114
#define IDR_MAINFRAME                   128
#define IDD_CHOOSEPROVIDER              129
#define IDD_JOINSESSION                 130
#define IDD_HOSTSESSION                 131
#define IDI_APPICON                     135
#define IDB_PIN_LL_SHADOW               153
#define IDB_PIN_LL_DYELLOW              154
#define IDB_PIN_S_SHADOW                155
#define IDB_PIN_S_DBLUE                 156
#define IDB_PIN_S_DGREEN                157
#define IDB_PIN_S_DYELLOW               158
#define IDB_PIN_S_GREEN                 159
#define IDB_MAPROOM                     161
#define IDB_RADAR_SCREEN                164
#define IDB_DASHBOARD                   166
#define IDD_GAME_OPTIONS                168
#define IDD_CAMPAIGN_SELECT             170
#define IDB_PLAYER2                     172
#define IDB_PLAYER3                     173
#define IDB_PLAYER4                     174
#define IDD_GAME_START                  175
#define IDB_TEAM                        176
#define IDB_TEAM_PICTURE                177
#define IDB_ARMYMAN                     178
#define IDD_TEAM_CREDITS                180
#define IDB_TITLE                       180
#define IDD_AUDIO_DIAGNOSTIC            181
#define IDB_OPTIONS                     183
#define IDB_QUIT                        184
#define IDD_TITLE                       186
#define IDB_3DO                         187
#define IDB_GRENADE_N                   188
#define IDB_GRENADE_F                   189
#define IDB_GRENADE_C                   191
#define IDD_HOSTLOBBY                   195
#define IDD_JOINLOBBY                   196
#define IDC_DEFAULT                     203
#define IDD_ERROR_BOX                   205
#define IDD_ERROR_BOX2                  206
#define IDC_HOST_PLAYERNAME             1001
#define IDC_VERSION                     1002
#define IDC_SP_TITLE                    1003
#define IDC_COPYRIGHT                   1003
#define IDC_COPYRIGHT1                  1003
#define IDC_GAMESETUP_TITLE             1004
#define IDC_ABOUTICON                   1004
#define IDC_HOST_TITLE                  1005
#define IDC_COPYRIGHT2                  1005
#define IDC_HOST_SESSION_TITLE          1006
#define IDC_COPYRIGHT3                  1006
#define IDC_HOST_PLAYER_TITLE           1007
#define IDC_COPYRIGHT4                  1007
#define IDC_JOIN_SESSION_TITLE          1008
#define IDCANEL                         1008
#define IDC_COPYRIGHT5                  1008
#define IDC_JOIN_PLAYER_TITLE           1009
#define IDC_DUEL_STATUSTEXT             1010
#define IDBACK                          1010
#define IDNEXT                          1011
#define ID_BACK                         1016
#define ID_NEXT                         1017
#define IDC_CAMPAIGN_MAPS               1018
#define ID_MORE                         1018
#define IDC_NEW_CAMPAIGN                1019
#define IDC_MISSION_0                   1019
#define IDC_MISSIONS_1                  1019
#define IDC_LOAD_CAMPAIGN               1020
#define IDC_MISSION_2                   1020
#define IDC_MISSIONS_2                  1020
#define IDC_SERVICEPROVIDERS            1021
#define IDC_LAST_CAMPAIGN               1021
#define IDC_MISSIONS_3                  1021
#define IDC_SELECT_CAMPAIGN_TITLE       1022
#define IDC_CHOOSE_PLAYER_TITLE         1023
#define IDC_SELECT_CAMPAIGN_TITLE2      1023
#define IDC_JOIN_SESSION                1024
#define IDC_GREEN_ARMY                  1024
#define IDC_HOST_SESSIONNAME            1025
#define IDC_TAN_ARMY                    1025
#define IDC_JOIN_PLAYERNAME             1026
#define IDC_BLUE_ARMY                   1026
#define IDC_HOSTSESSION                 1027
#define IDC_GREY_ARMY                   1027
#define IDC_JOINSESSION                 1028
#define IDC_GREEN_ARMY_BMP              1028
#define IDC_TAN_ARMY_BMP                1029
#define IDC_BLUE_ARMY_BMP               1030
#define IDC_GREY_ARMY_BMP               1031
#define IDC_SFX_OPTION_TITLE            1031
#define IDC_VOICE_OPTION_TITLE          1032
#define IDC_VOICE_OPTION_TITLE2         1032
#define IDC_SFX_OPTION_OFF_BUTTON       1033
#define IDC_SFX_OPTION_ON_BUTTON        1034
#define IDC_VOICE_OPTION_OFF_BUTTON     1035
#define IDC_SELECT_CAMPAIGN_TYPE_TITLE  1035
#define IDC_VOICE_OPTION_OFF_BUTTON2    1035
#define IDC_VOICE_OPTION_ON_BUTTON      1036
#define IDC_ONE_PLAYER_BUTTON           1036
#define IDC_VOICE_OPTION_ON_BUTTON2     1036
#define IDC_SFX_OPTION_ON_BUTTON2       1036
#define IDC_GROUP_BOX_1                 1037
#define IDC_MUSIC_OPTION_TITLE          1037
#define IDC_MUSIC_OPTION_TITLE3         1037
#define IDC_TWO_PLAYER_BUTTON           1038
#define IDC_MUSIC_OPTION_OFF_BUTTON     1038
#define IDC_MULTI_PLAYER_BUTTON         1039
#define IDC_MUSIC_OPTION_ON_BUTTON      1039
#define IDC_GROUP_BOX_2                 1040
#define IDC_DISCONNECT_BUTTON           1041
#define IDC_OPTIONS_BUTTON              1042
#define IDC_SFX_VOLUME_SLIDER           1042
#define IDC_GROUP_BOX_3                 1043
#define IDC_SFX_VOLUME_VALUE            1043
#define IDC_QUIT_BUTTON                 1044
#define IDC_SFX                         1044
#define IDC_VOICE                       1045
#define IDC_VOICE_SLIDER                1046
#define IDC_VOICE_VOLUME_SLIDER         1046
#define IDC_VOICE_VOLUME_VALUE          1047
#define IDC_VOICE_VOLUME_TITLE          1048
#define IDC_SFX_VOLUME_TITLE            1049
#define IDC_ARMY_GROUP_BOX              1050
#define IDC_MUSIC                       1050
#define IDC_SELECT_GROUP_BOX            1051
#define IDC_MUSIC_VOLUME_SLIDER         1051
#define IDC_ARMY_GROUP_BOX2             1052
#define IDC_MUSIC_VOLUME_VALUE          1052
#define IDC_MUSIC_VOLUME_TITLE          1053
#define IDC_SFX_PERCENT                 1054
#define IDC_VOICE_PERCENT               1055
#define IDC_MUSIC_PERCENT               1056
#define IDC_SFX_VOLUME_0                1057
#define IDC_SFX_VOLUME_100              1058
#define IDC_SFX_VOLUME_50               1059
#define IDC_VOICE_VOLUME_0              1060
#define IDC_VOICE_VOLUME_100            1061
#define IDC_VOICE_VOLUME_50             1062
#define IDC_MUSIC_VOLUME_0              1063
#define IDC_MUSIC_VOLUME_100            1064
#define IDC_MUSIC_VOLUME_50             1065
#define IDC_TEAM_TITLE                  1078
#define IDC_COPYRIGHT_TEAM              1080
#define ID_FINISH                       1081
#define IDC_AUDIO_DIAG_TITLE            1083
#define IDC_STREAM_GROUP                1084
#define IDC_SFX_GROUP                   1085
#define IDC_PLAY_AUDIO_BUTTON           1086
#define IDC_STOP_AUDIO_BUTTON           1087
#define IDC_AUDIO_LIST                  1088
#define IDC_AUDIO_BOX                   1089
#define IDC_EXIT_AUDIO_BUTTON           1090
#define IDC_VOICE_GROUP                 1091
#define IDC_TITLE_BKG                   1092
#define IDC_ONEPLYR                     1093
#define IDC_MULTIPLYR                   1094
#define IDC_OPTIONS                     1095
#define IDC_QUIT                        1096
#define IDC_MULTI_CAMPAIGN_MAPS         1097
#define IDC_MISSION_1                   1098
#define IDC_MISSION_3                   1099
#define IDC_SCENARIO_TITLE_0            1101
#define IDC_SCENARIO_TITLE_1            1102
#define IDC_SCENARIO_TITLE_2            1103
#define IDC_SCENARIO_TITLE_3            1104
#define IDC_MISSIONS_0                  1105
#define IDC_LIST2                       1107
#define IDC_LIST1                       1108
#define IDC_ERROR_STRING                1109
#define ID_RETRY                        1110
#define ID_SET_FRAME_TIME               32771
#define ID_TEMPORARY                    32774
#define ID_ENDCONNECT                   32776
#define ID_STARTGAME                    32777
#define ID_AVENUE                       32778
#define ID_CONTOUR                      32779
#define ID_FULLSCREEN                   32781
#define ID_ONE_PLAYER                   32781
#define ID_COMMANDER                    32782
#define ID_FAKEUNITS                    32784
#define ID_TWO_PLAYER                   32791
#define ID_MULTI_PLAYER                 32792
#define ID_DISCONNECT                   32793
#define ID_RUN_WINDOWED                 32795
#define ID_NICKY                        32796
#define ID_BOTHAI                       32797
#define ID_ROUTING                      32798
#define ID_SINGLE                       32799
#define ID_RANDOM                       32800
#define ID_JOYACTIVE                    32801
#define ID_SARGEID                      32802
#define ID_TESTDIALOG                   32803
#define ID_TESTDIALOG0                  32804
#define ID_ABSOLUTE                     32805
#define ID_OPTIONS                      32806
#define ID_PADS                         40012
#define ID_AUDIO_DIAGNOSTIC             40013
#define ID_FOG                          40014
#define ID_TESTDIALOG9                  40015
#define ID_TESTDIALOG10                 40016
#define ID_BITPADS                      40017
#define ID_ASSERT_UNTRAFFICABLE         40018
#define ID_INVULNERABLE                 40019
#define ID_MPSTART                      40020
#define ID_KEYPAD_AIMING                40022
#define ID_ARROW_AIMING                 40023
#define ID_BRACKET_AIMING               40024
#define ID_UNITBEHAVIOR                 40025
#define ID_HOST_TEST                    40026
#define ID_REMOTE_TEST                  40027
#define ID_MISSIONS_VISIBLE             40028
#define ID_BW01                         40029
#define ID_BW02                         40030
#define ID_SCRIPTDEBUG                  40031
#define ID_LABEL                        40032
#define ID_BW1                          40033
#define ID_BW2                          40034
#define ID_BW3                          40035
#define ID_BW4                          40036
#define ID_NO_CD_OK                     40037
#define IDS_WIZARD_FONTNAME             61204
#define IDS_DPERR_CLSID                 61205

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        206
#define _APS_NEXT_COMMAND_VALUE         40039
#define _APS_NEXT_CONTROL_VALUE         1111
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
