//=======================================================================
//     FILE:     sounds.h
//
//     CREATED:  Sunday, April 12, 1998 23:06:19
//
//=======================================================================

#define BAZOOKA_EXPLODE                     1000
#define MORTAR_EXPLODE                      1001
#define GRENADE_EXPLODE                     1002
#define MINE_EXPLODE                        1003
#define BIG_EXPLOSION                       1004
#define BARREL_EXPLODE                      1005
#define ROCK_HIT                            1006
#define WATER_EXPLODE                       1007
#define BULLET_HIT_OBJECT                   1008
#define WATER_HIT                           1009
#define DESTROYED                           1010
#define BULLET_HIT_TROOPER                  1011
#define EXPLODE_TROOPER                     1012
#define FLAME_HIT_TROOPER                   1013
#define BULLET_HIT_SARGE                    1014
#define SQUASH_SARGE                        1015
#define SQUASH_TROOPER                      1016
#define HIT_TROOPER1                        1017
#define HIT_TROOPER2                        1018
#define VEHICLE_HIGH_IMPACT                 1019
#define VEHICLE_LOW_IMPACT                  1020
#define BULLET_HIT_VEHICLE                  1021
#define TRUCK_FULL_LOOP                     1022
#define HT_FULL_LOOP                        1023
#define JEEP_FULL_LOOP                      1024
#define TANK_FULL_LOOP                      1025
#define FLAME_BEGIN                         1026
#define FLAME_LOOP                          1027
#define FLAME_END                           1028
#define HEAVY_MG                            1029
#define LIGHT_MG                            1030
#define MEDIUM_MG                           1031
#define CANNON                              1032
#define BAZOOKA                             1033
#define MORTAR                              1034
#define MORTAR_WHISTLE                      1035
#define GRENADE                             1036
#define RIFLE                               1037
#define TOWER_GUN                           1038
#define PLANE_SOUND                         1039
#define WEAPON_ACTIVATE                     1040
#define STEPS                               1041
#define SWAMP_STEPS                         1042
#define DESERT_SOUND1                       1043
#define DESERT_SOUND2                       1044
#define BAYOU_SOUND1                        1045
#define BAYOU_SOUND2                        1046
#define ALPINE_SOUND1                       1047
#define ALPINE_SOUND2                       1048
#define BUTTONSPRINGIN                      1049
#define CHOPPER_LOOP                        1050
#define AIR_RAID_LOOP                       1051
#define CHUGGA_LOOP                         1052
#define TICKING_LOOP                        1053
#define ALARM_LOOP                          1054
#define SARGE_FULLY_LOADED                  1055
#define PORTAL                              1056
#define TROOPER_DIE1                        1057
#define TROOPER_DIE2                        1058
#define TROOPER_DIE3                        1059
#define TROOPER_DIE4                        1060
#define TROOPER_DIE5                        1061
#define TROOPER_DIE6                        1062
#define TROOPER_DIE7                        1063
#define TROOPER_DIE8                        1064

//=======================================================================
//                                  EOF
//=======================================================================

