//=======================================================================
//     FILE:     streams.h
//
//     CREATED:  Saturday, March 21, 1998 19:17:57
//
//=======================================================================

#define TITLE_MUSIC                         2000
#define ALPINE1_MUSIC                       2001
#define ALPINE2_MUSIC                       2002
#define DESERT1_MUSIC                       2003
#define DESERT2_MUSIC                       2004
#define BAYOU1_MUSIC                        2005
#define BAYOU2_MUSIC                        2006
#define BAYOU3_MUSIC                        2007
#define WIN_MUSIC                           2008
#define LOSE_MUSIC                          2009

//=======================================================================
//                                  EOF
//=======================================================================

