//=======================================================================
//     FILE:     voices.h
//
//     CREATED:  Friday, April 17, 1998 09:19:11
//
//=======================================================================

#define THERE_HE_IS                         4000
#define GET_HIM                             4001
#define HES_OURS                            4002
#define YOURE_TOAST                         4003
#define TAN_SCUM                            4004
#define GREY_SCUM                           4005
#define REQUEST_PARATROOPERS                4006
#define SEND_PARATROOPERS                   4007
#define REQUEST_RECON                       4008
#define SEND_RECON                          4009
#define REQUEST_AIR_STRIKE                  4010
#define NEED_AIR_STRIKE                     4011
#define GREEN_SQUAD_ATTACK                  4012
#define GREEN_ATTACK                        4013
#define TAN_SQUAD_ATTACK                    4014
#define TAN_ATTACK                          4015
#define BLUE_SQUAD_ATTACK                   4016
#define BLUE_ATTACK                         4017
#define GREY_SQUAD_ATTACK                   4018
#define GREY_ATTACK                         4019
#define GREEN_SQUAD_DEFEND                  4020
#define GREEN_DEFEND                        4021
#define TAN_SQUAD_DEFEND                    4022
#define TAN_DEFEND                          4023
#define BLUE_SQUAD_DEFEND                   4024
#define BLUE_DEFEND                         4025
#define GREY_SQUAD_DEFEND                   4026
#define GREY_DEFEND                         4027
#define GET_OVER_HERE                       4028
#define FOLLOW_ME                           4029
#define SARGE_FOUND_AUTO_RIFLE              4030
#define SARGE_FOUND_FIRST_AID               4031
#define SARGE_FOUND_BAZOOKA                 4032
#define SARGE_FOUND_MINES                   4033
#define SARGE_FOUND_GRENADES                4034
#define SARGE_FOUND_MINESWEEPER             4035
#define SARGE_FOUND_MORTARS                 4036
#define SARGE_FOUND_NOTE                    4037
#define SARGE_FOUND_FLAMER                  4038
#define SARGE_FOUND_FLAG                    4039
#define SARGE_FOUND_EXPLOSIVES              4040
#define SARGE_FOUND_GREEN_FLAG              4041
#define SARGE_FOUND_TAN_FLAG                4042
#define SARGE_FOUND_BLUE_FLAG               4043
#define SARGE_FOUND_GREY_FLAG               4044
#define SARGE_FOUND_KEY1                    4045
#define SARGE_FOUND_KEY2                    4046
#define SARGE_FOUND_KEY3                    4047
#define SARGE_FOUND_AIRSTRIKE               4048
#define SARGE_FOUND_PARATROOPERS            4049
#define SARGE_FOUND_RECON                   4050
#define LOAD_TRUCKS_QUICK                   4051
#define GET_OUT_OF_HERE                     4052
#define GET_OUT_OF_TOWN                     4053
#define PLASTIC_FOR_INFO                    4054
#define PURSUING_RIFLE_SQUAD                4055
#define SPOTTED_BY_RIFLE_SQUAD              4056
#define PURSUING_BAZOOKA_SQUAD              4057
#define SPOTTED_BY_BAZOOKA_SQUAD            4058
#define PURSUING_FLAMER_SQUAD               4059
#define SPOTTED_BY_FLAMER_SQUAD             4060
#define PURSUING_MORTAR_SQUAD               4061
#define SPOTTED_BY_MORTAR_SQUAD             4062
#define PURSUING_SPY                        4063
#define SPOTTED_BY_SPY                      4064
#define ATTACKING_TANK                      4065
#define TANK_ATTACKING                      4066
#define ATTACKING_JEEP                      4067
#define JEEP_ATTACKING                      4068
#define ATTACKING_PARATROOPERS              4069
#define PARATROOPERS_ATTACKING              4070
#define GETTING_SHELLED                     4071
#define BEEN_BOMBED                         4072
#define ATTACKING_RIFLE_SQUAD               4073
#define RIFLE_SQUAD_ATTACKING               4074
#define ATTACKING_BAZOOKA_SQUAD             4075
#define BAZOOKA_SQUAD_ATTACKING             4076
#define ATTACKING_FLAMER_SQUAD              4077
#define FLAMER_SQUAD_ATTACKING              4078
#define ATTACKING_MORTAR_SQUAD              4079
#define MORTAR_SQUAD_ATTACKING              4080
#define ATTACKING_SPY                       4081
#define SPY_ATTACKING                       4082
#define MENDOWN                             4083
#define MENDOWN_2                           4084
#define TAKING_HEAVY_CASUALTIES             4085
#define NO_ONE_HERE                         4086
#define ALL_CLEAR_SARGE                     4087
#define WAITING_FOR_ORDERS                  4088
#define READY_AIM_FIRE                      4089
#define PINNED_DOWN                         4090
#define WHERE_FROM                          4091
#define DONE_LOADING                        4092
#define IM_HIT                              4093
#define SQUAD_READY                         4094
#define SQUAD_AIM                           4095
#define SQUAD_FIRE                          4096
#define YESSIR                              4097
#define AFFIRMATIVE                         4098
#define ONWAY                               4099
#define APPROACHING                         4100
#define DESTINATION                         4101
#define NOPARAS                             4102
#define AAGUNS                              4103
#define NOAIR                               4104
#define HALT_INTRUDER                       4105
#define HALT                                4106
#define DS1M1                               4107
#define DS1M2                               4108
#define DS1M3                               4109
#define DS2M1                               4110
#define DS2M2                               4111
#define DS3M1                               4112
#define DS3M2                               4113
#define DS4M1                               4114
#define DS4M2                               4115
#define AS1M1                               4116
#define AS1M2                               4117
#define AS2M1                               4118
#define AS2M2                               4119
#define AS3M1                               4120
#define AS3M2                               4121
#define AS3M3                               4122
#define AS4M1                               4123
#define AS4M2                               4124
#define BS1M1                               4125
#define BS1M2                               4126
#define BS2M1                               4127
#define BS2M2                               4128
#define BS3M1                               4129
#define BS3M2                               4130
#define BS3M3                               4131
#define BS4M1                               4132
#define BS4M2                               4133
#define BS4M3                               4134
#define DESERT1_1LOSE                       4135
#define DESERT1_1WIN                        4136
#define DESERT1_2LOSE                       4137
#define DESERT2_1LOSE                       4138
#define DESERT2_2LOSE                       4139
#define DESERT2_2WIN                        4140
#define DESERT3_1LOSE                       4141
#define DESERT3_2LOSE                       4142
#define DESERT4_1LOSE                       4143
#define DESERT_DIE                          4144
#define DESERT_LOSE                         4145
#define DESERT_WIN                          4146
#define DESERT_MP_DIE                       4147
#define DESERT_MP_LOSE                      4148
#define DESERT_MP_WIN                       4149
#define ALPINE1_1LOSE                       4150
#define ALPINE1_1WIN                        4151
#define ALPINE1_2LOSE                       4152
#define ALPINE1_2WIN                        4153
#define ALPINE2_1LOSE                       4154
#define ALPINE2_1WIN                        4155
#define ALPINE2_2LOSE                       4156
#define ALPINE2_2WIN                        4157
#define ALPINE3_1LOSE                       4158
#define ALPINE3_1WIN                        4159
#define ALPINE3_2LOSE                       4160
#define ALPINE3_2WIN                        4161
#define ALPINE3_3LOSE                       4162
#define ALPINE3_3WIN                        4163
#define ALPINE4_1LOSE                       4164
#define ALPINE4_1WIN                        4165
#define ALPINE4_2LOSE                       4166
#define ALPINE4_2WIN                        4167
#define ALPINE_DIE                          4168
#define ALPINE_LOSE                         4169
#define ALPINE_WIN                          4170
#define ALPINE_MP_DIE                       4171
#define ALPINE_MP_LOSE                      4172
#define ALPINE_MP_WIN                       4173
#define BAYOU1_1LOSE                        4174
#define BAYOU1_1WIN                         4175
#define BAYOU1_2LOSE                        4176
#define BAYOU1_2WIN                         4177
#define BAYOU2_1LOSE                        4178
#define BAYOU2_1WIN                         4179
#define BAYOU2_2LOSE                        4180
#define BAYOU2_2WIN                         4181
#define BAYOU3_1LOSE                        4182
#define BAYOU3_1WIN                         4183
#define BAYOU3_2LOSE                        4184
#define BAYOU3_2WIN                         4185
#define BAYOU3_3LOSE                        4186
#define BAYOU3_3WIN                         4187
#define BAYOU4_1LOSE                        4188
#define BAYOU4_1WIN                         4189
#define BAYOU4_2LOSE                        4190
#define BAYOU4_2WIN                         4191
#define BAYOU4_3LOSE                        4192
#define BAYOU_DIE                           4193
#define BAYOU_LOSE                          4194
#define BAYOU_WIN                           4195
#define BAYOU_MP_DIE                        4196
#define BAYOU_MP_LOSE                       4197
#define BAYOU_MP_WIN                        4198
#define CRATE_LOAD                          5000
#define TRAIN_HORN                          5001
#define GATE_CLOSE                          5002
#define CHOPPER_SPIN_DOWN                   5003
#define CHOPPER_SPIN_UP                     5004
#define GATE_OPEN                           5005
#define TRAIN_SCREECH                       5006
#define TRAIN_WRECK                         5007
#define CEMETARY_GATE_CLOSE                 5008
#define CEMETARY_GATE_OPEN                  5009
#define SPLASH                              5010
#define SARGE_LOW_HEALTH                    5011
#define HEAL_SARGE                          5012
#define DESTROYED_SCRIPT                    5013
#define DS2M1B                              5014
#define DS3M1B                              5015
#define DS3M2B                              5016
#define AS4M1_1                             5017
#define AS4M1_2                             5018
#define AS4M1_3                             5019
#define BS3M1MID                            5020
#define D12MID                              5021
#define D31BAD                              5022
#define BAYOU1_1M                           5023
#define BAYOU3_1M                           5024
#define BAYOU3_2M                           5025
#define BAYOU4_1M                           5026
#define DESERT1_2M                          5027
#define DESERT2_2M                          5028
#define ALPINE1_1M                          5029
#define ALPINE2_1M                          5030
#define ALPINE3_1SARGE                      5031
#define ALPINE3_1M                          5032
#define ALPINE4_2SARGE                      5033
#define ALPINE1_1M2                         5034
#define ALPINE3_1M2                         5035
#define ALPINE3_1M3                         5036
#define SARGE_GETTOMED                      5037
#define SARGE_DONTLEAVE                     5038

//=======================================================================
//                                  EOF
//=======================================================================

